### ISSUE TITLE
Push new version to crates.io?

### ISSUE THREAD

**Issue by GravityScore** [jeaye/ncurses-rs#101]
Could we have the latest version of this repository uploaded to crates.io? I'm trying to publish a crate that depends on this one, and I need features from the latest version of this repository on GitHub - the crates.io version is too old. I can't seem to reference GitHub dependencies in published crates, so would you be able to publish a new version on crates.io?

**Comment by jeaye** [comment]
I'm on it. Uno momento.

**Comment by jeaye** [comment]
Updated to 5.80.0 on crates; cheers!

**Comment by GravityScore** [comment]
Thank you!
