### ISSUE TITLE
Online documentation needed

### ISSUE THREAD

**Issue by osa1** [jeaye/ncurses-rs#105]
Maybe because I'm a Rust noob, but I can't find documentation anywhere. "Documentation" link in Crates.io page redirects to this Github page, but there's no online documentation as far as I can see.

**Comment by jeaye** [comment]
@osa1 ncurses-rs has the same exact API as the C ncurses API; it's just a very thin wrapper. To provide ncurses-rs docs would be to duplicate the official docs, which seems unwise. For any function in ncurses-rs, have a look at the ncurses docs for how it's used.

**Comment by osa1** [comment]
Um.. no. Surely `ll` module is _thin_, but the main module is not. For example, how am I supposed to know what argument `curs_set` is expecting? In the original ncurses API it's an `int`, but `ncurses-rs` defined an enum for that, `CURSOR_VISIBILITY`, and the only way to learn this is to read the source. This is far from ideal - ideally we'd have documentation.

**Comment by exrok** [comment]
I found this thread well having the same problems as @osa1 with the CURSOR_VISIBILITY and had to also search through the source code to find out what to do. I also agree that this is not ideal.
