### ISSUE TITLE
`ncurses::stdscr` will require unsafe block

### ISSUE THREAD

**Issue by gyscos** [jeaye/ncurses-rs#115]
Using latest Rust nightly, accessing static extern require unsafe (see https://github.com/rust-lang/rust/issues/35112):

The examples now produce this error:
```
% rustc --version
rustc 1.13.0-nightly (55bf6a4f8 2016-09-18)
% cargo build --example ex_2
   Compiling ncurses v5.82.0 (file:///home/gyscos/fetched/ncurses-rs)
warning: use of extern static requires unsafe function or block (error E0133), #[warn(safe_extern_statics)] on by default
  --> examples/ex_2.rs:23:10
   |
23 |   keypad(stdscr, true);
   |          ^^^^^^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue 36247 <https://github.com/rust-lang/rust/issues/35112>

    Finished debug [unoptimized + debuginfo] target(s) in 0.21 secs
```

**Comment by jeaye** [comment]
Thanks for the report! Do you feel comfortable sending in a PR for this?

**Comment by gyscos** [comment]
#116 moves these variables to an internal module, and exposes safe wrapper functions instead. Examples have been updated.

NOTE: since it changes those from variable to functions, it probably breaks most code that use those.
I'm not sure how to solve this issue without going through a function though.
