### ISSUE TITLE
`chtype` (and so `attr_t`) is 64bits on Ubuntu 16.10

### ISSUE THREAD

**Issue by gyscos** [jeaye/ncurses-rs#119]
* On my machine (archlinux with ncurses 6.0 installed), `/usr/include/ncurses.h` contains:
```c
#if 1 && defined(_LP64)
typedef unsigned chtype;
typedef unsigned mmask_t;
# else
typedef uint32_t chtype;
typedef uint32_t mmask_t;
#endif
```
This results in a 32bits `chtype`.

* On a Ubuntu 16.10 docker image (with libncursesw5-dev installed), `/usr/include/ncursesw/ncurses.h` contains:
```c
#if 0 && defined(_LP64)
typedef unsigned chtype;
typedef unsigned mmask_t;
#else
typedef unsigned long chtype;
typedef unsigned long mmask_t;
#endif
```
This results in a 64bits `chtype`.

ncurses-rs assumes it is 32 bits, so this type mismatch can cause big troubles in functions like `attr_get` where ncurses overwrites some extra bytes.

**Comment by gyscos** [comment]
Looks like a duplicate of #44 - not sure why it's still an issue

**Comment by gyscos** [comment]
Note: the problem is that selecting the correct type for `ll::chtype` does not just depend on the architecture, but also on the local ncurses version (5 vs 6), which sounds a bit more complicated - might need a build script to get the correct size at compile time.

**Comment by gyscos** [comment]
Weird thing is that on ubuntu, `libncurses5-dev` is at version 6.0, and the `ncurses.h` indeed contains:
```c
/* These are defined only in curses.h, and are used for conditional compiles */
#define NCURSES_VERSION_MAJOR 6
#define NCURSES_VERSION_MINOR 0
#define NCURSES_VERSION_PATCH 20160213

/* This is defined in more than one ncurses header, for identification */
#undef  NCURSES_VERSION
#define NCURSES_VERSION "6.0"
```
Though it's definitely a "version 5" ncurses, with `/lib/x86_64-linux-gnu/libncursesw.so.5` and such... Rather confusing - and this means checking for NCURSES_VERSION is not enough to detect the actual version installed.

**Comment by gyscos** [comment]
Should be fixed, now waiting for next version on crates.io

**Comment by jeaye** [comment]
Published!
