### ISSUE TITLE
Performance problem when creating a new window

### ISSUE THREAD

**Issue by JacksonGariety** [jeaye/ncurses-rs#126]
I use ncurses programs like `cmus` and `wifi-menu` and I never run into performance issues. However, `ncurses-rs` seems to flicker when calling `doupdate()` (or `refresh()`) after a call to `newwin()`. I've created an example program which demonstrates the flicker.

I'm wondering if it's an isssue with the program, an issue with ncurses, or an issue with my code:

```rust
extern crate ncurses;

use std::{thread, time};
use ncurses::*;

fn main () {
    initscr();
    refresh();

    // sleep for 3
    thread::sleep(time::Duration::new(3, 0));

    let win = newwin(0,0,0,0);
    wnoutrefresh(win);
    doupdate();

    // sleep for 3
    thread::sleep(time::Duration::new(3, 0));
    endwin();
}
```

Thanks.

**Comment by jeaye** [comment]
The first thing I'd try is to write the same exact program in C, which should be simple, since ncurses-rs is such a thin wrapper. If the program has the same issue in C, then it's an issue with the ncurses usage, not the wrapper.

**Comment by JacksonGariety** [comment]
@jeaye Okay I translated the program into C and there is no flicker:

```
#include <curses.h>
#include <unistd.h>

int main(void) {
    WINDOW * win;
    initscr();
    win = newwin(0,0,0,0);

    sleep(3);

    wnoutrefresh(win);
    doupdate();

    sleep(3);
}
```

**Comment by JacksonGariety** [comment]
Update: I was able to reproduce this in C after all. I think it has something to do with the terminal being used but I can't be sure.

Sorry to trouble.
