### ISSUE TITLE
Can't print chars like ✔?

### ISSUE THREAD

**Issue by AmarOk1412** [jeaye/ncurses-rs#147]
Hei!

Nice work. I'm currently trying the library. Now, i'm trying to print characters like emojis (or others things). And `mvprintw(LINES() - 2, 1, "✔")` gives me weird symbols. Any way to print this correctly?

Have a nice day!

**Comment by jeaye** [comment]
@AmarOk1412 Hey, thanks for the report. Have you tried the same code in C to verify it should work?

The relevant `printw` implementation for ncurses-rs is here: https://github.com/jeaye/ncurses-rs/blob/master/src/ncurses.rs#L1104

You may also need to enable the `wide` feature. For example: `cargo run --features "wide"`

**Comment by AmarOk1412** [comment]
nop didn't tried yet. I'll try this ASAP and dig if it doesn't work.

**Comment by AmarOk1412** [comment]
Don't really have the time for now. I didn't tried the code in C. Need to do it this week end. But I tried with this in my Cargo.

```

[dependencies.ncurses]
version = "5.91.0"
default-features = false
features = ["wide"]
```

**Comment by AmarOk1412** [comment]
Gotcha... my bad.

```rust
let locale_conf = LcCategory::all;
setlocale(locale_conf, "");
```

it works better with this...

**Comment by jeaye** [comment]
Glad you sorted it out! Best of luck.
