### ISSUE TITLE
`wmouse_trafo` should take a `*const WINDOW`

### ISSUE THREAD

**Issue by czipperz** [jeaye/ncurses-rs#174]
If you look up `wmouse_trafo`, you will see that it should take a `const WINDOW*` https://linux.die.net/man/3/mouse_trafo.  Here are the places that take it mutably:

https://github.com/jeaye/ncurses-rs/blob/5cefed9fb6c100ff5d678ad8e598dd39b821bdfd/src/ll.rs#L378
https://github.com/jeaye/ncurses-rs/blob/5cefed9fb6c100ff5d678ad8e598dd39b821bdfd/src/lib.rs#L1997

**Comment by czipperz** [comment]
I believe the correct thing to do is replace `*mut WINDOW` with just `WINDOW` as used in the other functions in these files.

**Comment by jeaye** [comment]
Thanks! This is now published.
