### ISSUE TITLE
Unicode broken on rust-1.32

### ISSUE THREAD

**Issue by kamiyaa** [jeaye/ncurses-rs#180]
Unicode is broken on rust-1.32
Specifically, `addstr` and its family of functions.
Not entirely sure why it is broken.
an example would be `…` being printed as `~@`

```~ $ rustc --version
rustc 1.32.0 (9fda7c223 2019-01-16)
```
`ncurses-6.1`

**Comment by simmons** [comment]
I also observed this problem, and tracked it down to memory corruption in the unsafe Rust code wrapping the `setlocale()` function.  See PR #181.

**Comment by kamiyaa** [comment]
Fixed via 8400b5a06558438ddb937d84cd589ec951769f84
