### ISSUE TITLE
Where is the source for published crate version 5.101.0?

### ISSUE THREAD

**Issue by jclulow** [jeaye/ncurses-rs#208]
It seems like the current source in the `master` branch does not match the latest published package.  Where is the source for 5.101.0?  Cheers.

**Comment by jeaye** [comment]
Looks like I made the commit, published, and never pushed it. The commit for 5.101.0 is here: https://github.com/jeaye/ncurses-rs/commit/b68b6d616596223c67b7892d19e50dedb02b197d
