### ISSUE TITLE
ABI Problems on 64-bit Debian

### ISSUE THREAD

**Issue by Nitori-** [jeaye/ncurses-rs#44]
The ABI for chtype isn't quite correct in `src/ll.rs` on Debian. For some reason Debian on amd64 compiles ncurses with the `--disable-lp64` option (probably to be ABI backwards compatible), causing `chtype` to be an `unsigned long` instead of an `unsigned int`. This leads to some strange things happening when using eg. `box_(0,0)`.

I don't know enough Rust yet to know what a good fix for this is (I don't know if there's a good way to pull a typedef out of a C header file), but at least if somebody else hits it they might see this. My fix is just to switch distros :smile:.

**Comment by NewbiZ** [comment]
Oh god... I just spent 2 hours trying to figure out why I had some box corners disappearing. Just saved my day.

**Comment by NewbiZ** [comment]
Debian source package available as git repo here: git://anonscm.debian.org/collab-maint/ncurses.git

Relevant changelog entries (`NEWS`):

    2005-09-17:
        + modify default for --disable-lp64 configure option to reduce impact
          on existing 64-bit builds.  Enabling the _LP64 option may change the
          size of chtype and mmask_t.  However, for ABI 6, it is enabled by
          default (report by Mike Frysinger).

    2005-03-26:
        + add ifdef's for _LP64 in curses.h to avoid using wasteful 64-bits for
          chtype and mmask_t, but add configure option --disable-lp64 in case
          anyone used that configuration.

Relevant part of the `configure.in`:

          ###   use option --disable-lp64 to allow long chtype
          case $cf_cv_abi_version in
          [[345]]*)
                  default_with_lp64=no
                  ;;
          *)
                  default_with_lp64=yes
                  ;;
          esac
          
          AC_MSG_CHECKING(whether to enable _LP64 definition in curses.h)
          AC_ARG_ENABLE(lp64,
                  [  --disable-lp64          allow chtype to be long (ignore _LP64)],
                  [with_lp64=$enableval],
                  [with_lp64=$default_with_lp64])
          AC_MSG_RESULT($with_lp64)
          
          if test "x$with_lp64" = xyes ; then
                  cf_cv_enable_lp64=1
          else
                  cf_cv_enable_lp64=0
          fi
          AC_SUBST(cf_cv_enable_lp64)

This parameter is then used to template the `curses.h` header quoted in my previous post, from `curses.h.in`:

          #if @cf_cv_enable_lp64@ && defined(_LP64)
          typedef unsigned chtype;
          typedef unsigned mmask_t;
          #else
          typedef @cf_cv_typeof_chtype@ chtype;
          typedef @cf_cv_typeof_mmask_t@ mmask_t;
          #endif

And of course the `INSTALL` doc:

              --disable-lp64
                  The header files will ignore use of the _LP64 symbol to make chtype
                  and mmask_t types 32 bits (they may be long on 64-bit hosts, for
                  compatibility with older releases).

                  NOTE: this is potentially an ABI change, depending on existing
                  packages.  The default for this option is "disabled" for ncurses
                  ABI 5, and "enabled" for ABI 6.

So this behavior is supposed to change for ABI 6, but I don't see that coming soon. I checked on Debian testing and unstable, and they are still shipping 5.9:

    squeeze (oldstable): 5.7+20100313-5
    wheezy (stable): 5.9-10
    jessie (testing): 5.9+20140913-1+b1
    sid (unstable): 5.9+20140913-1+b1, 5.9+20140913-1

**Comment by NewbiZ** [comment]
> My fix is just to switch distros :smile:.

I've checked upstream sources and the config come from there. So I guess at least any `amd64` distro should have this behavior. Am I incorrect?

**Comment by NewbiZ** [comment]
Since this is an upstream decision, i made the following changes:

In `lib/ll.rs`:
- `ll::chtype` is now `c_ulong` on `target_arch = "x86_64"`, `c_uint` otherwise.
- `ll::mmask_t` is now `ll::chtype`.
- `ll::attr_t` is now `ll::chtype`.

In `lib/scurses.rs`:
- `ncurses::chtype` is now the rust native equivalent of `ll::chtype` (`u32` when `ll:chtype` is `c_uint`, `u64` when `ll::chtype` is `c_ulong`)
- All wrappers now use `ncurses::chtype` instead of `u32`.

 This would need to be tested on a 32b distro. I can make a pull request if needed.
