### ISSUE TITLE
Submit to crates.io

### ISSUE THREAD

**Issue by marcusklaas** [jeaye/ncurses-rs#53]
There currently isn't a wrapper for ncurses on crates.io. This repo would be a good start!

**Comment by Gonzih** [comment]
Yes, that would be great!

**Comment by jeaye** [comment]
I'm not familiar with what this entails. My Rust usage these days extends only as far as maintaining this package. So, I willingly accept PRs and have been looking for a steady and trustworthy contributer to which I can give contributer access.

**Comment by leshow** [comment]
https://github.com/jeaye/ncurses-rs/pull/70/

crates is rust's package manager, adding your library to crates.io allows people to easily list your project as a dependency and automatically update when new versions are pushed, etc.

**Comment by leshow** [comment]
should be able to close this now, it's on crates.io: https://crates.io/crates/ncurses

**Comment by marcusklaas** [comment]
Nice.
