### ISSUE TITLE
Does not build with latest nightly build (2015-01-12)

### ISSUE THREAD

**Issue by farrel** [jeaye/ncurses-rs#63]
± % rustc --version
    rustc 1.0.0-nightly (3d0d9bb6f 2015-01-12 22:56:20 +0000)

    ± % cargo build
    Compiling ncurses v5.71.1 (https://github.com/jeaye/ncurses-rs.git#4dc62c21)
    src/ncurses.rs:13:12: 13:17 warning: feature has been added to Rust, directive not necessary
    src/ncurses.rs:13 #![feature(globs)]
                             ^~~~~
    src/ncurses.rs:14:12: 14:23 warning: feature has been added to Rust, directive not necessary
    src/ncurses.rs:14 #![feature(macro_rules)]
                             ^~~~~~~~~~~
    src/constants.rs:186:35: 186:43 error: `$b:expr` is followed by `$m:expr`, which is not allowed for `expr` fragments
    src/constants.rs:186 macro_rules! ncurses_mouse_mask( ($b: expr $m: expr) => ($m << (($b - 1) * 5)); );
                                                       ^~~~~~~~
    src/constants.rs:233:31: 233:39 error: `$e:expr` is followed by `$x:expr`, which is not allowed for `expr` fragments
    src/constants.rs:233 macro_rules! button_release( ($e: expr $x: expr) => (e & ncurses_mouse_mask!(x 0x001)); );
                                                   ^~~~~~~~
    src/constants.rs:234:29: 234:37 error: `$e:expr` is followed by `$x:expr`, which is not allowed for `expr` fragments
    src/constants.rs:234 macro_rules! button_press( ($e: expr $x: expr) => (e & ncurses_mouse_mask!(x 0x002)); );
                                                 ^~~~~~~~
    src/constants.rs:235:29: 235:37 error: `$e:expr` is followed by `$x:expr`, which is not allowed for `expr` fragments
    src/constants.rs:235 macro_rules! button_click( ($e: expr $x: expr) => (e & ncurses_mouse_mask!(x 0x004)); );
                                                 ^~~~~~~~
    src/constants.rs:236:36: 236:44 error: `$e:expr` is followed by `$x:expr`, which is not allowed for `expr` fragments
    src/constants.rs:236 macro_rules! button_double_click( ($e: expr $x: expr) => (e & ncurses_mouse_mask!(x 0x008)); );
                                                        ^~~~~~~~
    src/constants.rs:237:36: 237:44 error: `$e:expr` is followed by `$x:expr`, which is not allowed for `expr` fragments
    src/constants.rs:237 macro_rules! button_triple_click( ($e: expr $x: expr) => (e & ncurses_mouse_mask!(x 0x010)); );
                                                        ^~~~~~~~
    src/constants.rs:238:38: 238:46 error: `$e:expr` is followed by `$x:expr`, which is not allowed for `expr` fragments
    src/constants.rs:238 macro_rules! button_reserved_event( ($e: expr $x: expr) => (e & ncurses_mouse_mask!(x 0x020)); );

**Comment by jeaye** [comment]
Bam. Try meow? I just merged a somewhat-stale PR.

**Comment by farrel** [comment]
Works!
