### ISSUE TITLE
Build fails on Rust Beta

### ISSUE THREAD

**Issue by PaulJuliusMartinez** [jeaye/ncurses-rs#73]
I'm trying to build a project with ncurses and get the following error when running cargo build:

```
    Compiling ncurses v5.72.0 (https://github.com/jeaye/ncurses-rs#7a019596)
/Users/Paul/.cargo/git/checkouts/ncurses-rs-19e4d6676c1c76f9/master/src/ncurses.rs:15:1: 15:18 error: unstable feature
/Users/Paul/.cargo/git/checkouts/ncurses-rs-19e4d6676c1c76f9/master/src/ncurses.rs:15 #![feature(core)]
                                                                                      ^~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error
Could not compile `ncurses`.
```

**Comment by sru** [comment]
> During the alpha cycle, the use of unstable APIs and language features was permitted, but triggered a warning. As of the Beta release, the use of unstable APIs will become an error (unless you are using Nightly builds or building from source).
from http://blog.rust-lang.org/2015/04/03/Rust-1.0-beta.html

I was fiddling around and learning Rust (making a snake game with ncurses). I got ncurses compiling with a little modification. I assume the functionality be the same, but since I don't know the difference between `core` and `std`, I cannot guarantee it.
```diff
diff --git a/src/ncurses.rs b/src/ncurses.rs
index 30a4ad6..28cb67a 100644
--- a/src/ncurses.rs
+++ b/src/ncurses.rs
@@ -12,12 +12,10 @@
 #![crate_type = "lib"]
 #![allow(non_camel_case_types)]
 #![allow(non_snake_case)]
-#![feature(core)]
 
-extern crate core;
 extern crate libc;
 
-use core::mem;
+use std::mem;
 use std::{ char, ptr };
 use std::ffi::{CString, CStr};
 use self::ll::{FILE_p};
```

I can make a pull request if it doesn't break anything.

**Comment by enricostano** [comment]
same error here, I'll try to build it from source using @sru hint

**Comment by enricostano** [comment]
oh it seems solved upstream https://github.com/jeaye/ncurses-rs/pull/74/files#diff-508797cbe7b9402f33609735dfeeb69dR18

so we'll get this change in next release I guess, meanwhile I'll try to use master branch from Cargo
