### ISSUE TITLE
Special ACS characters don't work

### ISSUE THREAD

**Issue by gyscos** [jeaye/ncurses-rs#80]
I'm not sure what's happening, considering the ACS methods are so thin, but the bug _is_ present: using, for instance, `addch(ACS_TTEE());` prints `^@` instead.
I tried with `ACS_ULCORNER`, or basically any other ACS_ method, and it always prints `^@` instead.

Note: using the box_ method (using the default characters) _does_ produce the correct result. It's just impossible to do it manually.

EDIT: it seems addch may be the culprit. `printw("┘");` works fine, but `addch('┘');` does not.

(I did some tests with the C ncurses library, and while `addch('┘');` does not work because `┘` does not fit in a byte, `addch(ACS_TTEE);` does work... :-S )

**Comment by Inityx** [comment]
In addition, printing fullwidth characters yields the "unknown character" symbol, printing with addch, addstr, or printw. Does this repository include functionality provided by ncursesw?

**Comment by jeaye** [comment]
Thanks for the report, and sorry for the delay. I'm not sure what's going on here. It appears you _are_ using the ncursesw library (enabled with the `wide` feature in cargo). With that aside, there must be a slight difference in the Rust and C APIs for `addch`. It's worth investigating more.

**Comment by lidavidm** [comment]
I've been running into this too. I'm thinking the `acs_map` of the special characters is not defined properly. For instance, `ACS_BULLET` under Rust is some crazy value that changes every time I run the program, while under C it is consistently `0x40007e`.

**Comment by lidavidm** [comment]
Hmm. `chtype` is defined as `c_ulong` (=`u64`) on x86_64. However, `ncurses.h` on my system has
```c
#if 1 && defined(_LP64)
typedef unsigned chtype;
typedef unsigned mmask_t;
#else
typedef uint32_t chtype;
typedef uint32_t mmask_t;
#endif
```
i.e. `chtype` is always 4 bytes. That's a problem given that `acs_map` is `[chtype; 0]`.
