### ISSUE TITLE
KEY_DC and KEY_IC use wrong code

### ISSUE THREAD

**Issue by Gyscos** [jeaye/ncurses-rs#83]
On my machine, KEY_DC is defined in ncurses.h as 0512, that is 330 or 0x14A.
However it is defined as 0x150 in constants.rs. I suspect a typo?

Similarly, KEY_IC sould be defined as 0513 = 0x14B, but is 0x151 in constans.rs.

**Comment by jeaye** [comment]
This is a duplicate of #2 which has yet to be resolved. Care to make a PR?

**Comment by Gyscos** [comment]
Sorry I missed that >_>
